accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='register'),
    path('guest/', views.guest_register_view, name='guest_register'),
]

carts/urls.py
from django.urls import path

from . import views

app_name='carts'

urlpatterns = [
    path('', views.cart_home, name='home'),
    path('update/', views.cart_update, name='update'),
    path('checkout/', views.checkout_home, name='checkout'),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from . import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePageView.as_view(), name='home'),
    path('about/', views.AboutPageView.as_view(), name='about'),
    path('contact/', views.ContactPageView.as_view(), name='contact'),
    path('account/', include('django.contrib.auth.urls')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('products/', include('products.urls', namespace='products')),
    path('search/', include('search.urls', namespace='search')),
    path('cart/', include('carts.urls', namespace='cart')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

from . import views

app_name='products'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='list'),
    #path('products/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('<slug:product_slug>/', views.ProductDetailSlugView.as_view(), name='detail'),
]

ecommerce/forms.py
from django import forms


class ContactForm(forms.Form):
    #name = forms.CharField()
    fullname = forms.CharField(widget = forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': "Name", 'name': 'fullname'
                }))
    email = forms.EmailField(required=True,
                widget = forms.EmailInput(attrs={
                'class': 'form-control', 'placeholder': "Your Email", 'name': 'Email'
                }))
    message = forms.CharField(widget=forms.Textarea(attrs=
        {'class': 'form-control'}))

    # def clean_email(self):
    #     """
    #     To only allow emails from gmail
    #     """
    #     email = self.cleaned_data.get("email")
    #     if not "gmail.com" in email:
    #         raise forms.ValidationError("Email has to be gmail.com")
    #     return email

ecommerce/views.py
from django.http import HttpResponse
from django.views.generic import TemplateView
from django.views.generic.edit import FormView
from .forms import ContactForm
from products.models import Product

class HomePageView(TemplateView):
    title = "Home!"
    content = "Explore Our featured Items"
    featured_products = Product.objects.featured()
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        context['title'] = self.title
        context['content'] = self.content
        context['featured_products'] = self.featured_products
        return context

class AboutPageView(TemplateView):
    title = "About"
    content = "Welcome to the about page"
    template_name = 'about.html'

    def get_context_data(self, **kwargs):
        context = super(AboutPageView, self).get_context_data(**kwargs)
        context.update({'title': self.title,
                        'content': self.content})
        return context

class ContactPageView(FormView):
    form_class = ContactForm
    title = "Contact"
    content = "Welcome to the contact page"
    template_name = 'contact/view.html'
    success_url = '/contact/'

    def form_valid(self, form):
        print(form.cleaned_data['email'])
        print(form.cleaned_data)
        return super(ContactPageView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ContactPageView, self).get_context_data(**kwargs)
        context.update({'title': self.title,
                        'content': self.content})
        return context

ecommerce/templates/base/css.html
{% load static %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"/>

<!-- font awesome css -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

ecommerce/templates/base/js.html
{% load static %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

ecommerce/templates/base/navbar.html
{%url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'about' as about_url %}
{% url 'products:list' as product_list_url %}
{% url 'login' as login_url %}
{% url 'accounts:register' as register_url %}
{% url 'logout' as logout_url %}
{% url 'cart:home' as cart_url %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{{ home_url }}">{% if brand_name %} {{ brand_name }} {% else %} Ecommerce {% endif %}</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == home_url %}active{% endif %}">
        <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
        <a class="nav-link" href="{{ contact_url }}">Contacts</a>
      </li>
      <li class="nav-item {% if request.path == product_list_url %}active{% endif %}">
        <a class="nav-link" href="{{product_list_url}}">Products</a>
      </li>
      <li class="nav-item {% if request.path == about_url %}active{% endif %}">
        <a class="nav-link" href="{{about_url}}">About</a>
      </li>
      {% if user.is_authenticated %}
        <li class="nav-item {% if request.path == logout_url %}active{% endif %}">
          <a class="nav-link" href="{{ logout_url }}">Logout</a>
        </li>
      {% else %}
      <li class="nav-item {% if request.path == register_url %}active{% endif %}">
        <a class="nav-link" href="{{ register_url }}">Sign Up</a>
      </li>
        <li class="nav-item {% if request.path == login_url %}active{% endif %}">
          <a class="nav-link" href="{{ login_url }}">Login</a>
        </li>
      {% endif %}
      <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
        <a class="nav-link" href="{{ cart_url }}">{{ request.session.cart_items }} <i class="fas fa-shopping-cart"></i> </a>
      </li>
    </ul>
    {% include 'search/snippets/search-form.html' %}
  </div>
</nav>